### ISSUE TITLE
Demonstrate reputation calculation over Holochain data

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_lang#4]
Integrate the reputation DSL with some REA event data coming from a Holo-REA module and make calculation execution workable

**Comment by mhuesch** [comment]
this is subsumed by https://github.com/sacredcapital/rep_interchange/issues/8, although that will only demonstrate calculations over simple types.

however, we are already tracking user-defined types in #54, and implementing that, plus https://github.com/sacredcapital/rep_interchange/issues/8 above, should subsume the entire issue here. closing.
