### ISSUE TITLE
Automatic conversions between units using TCons to represent OM-typed data

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_lang#6]
Rather than implementing OM itself in Rust (something akin to [Dimensional](https://hackage.haskell.org/package/dimensional) in Haskell), a simpler (but much less performant) option may be to embed an RDF reasoner that leverages the [OM RDF ontology](https://github.com/HajoRijgersberg/OM) directly.

See https://github.com/HajoRijgersberg/OM#libs for some implementations of OM unit conversions in other languages.

**Comment by mhuesch** [comment]
subsumed, for implementation purposes, by #13.

embedding an RDF reasoner into `rep_lang` seems out of scope for now, and I think we will remember to check this issue if/when we come up against something which necessitates that.
