### ISSUE TITLE
Proof execution against custom types provided to the interpreter

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_lang#7]
This could form part of the test suite for #5 as a first pass.

Refer to https://github.com/sacredcapital/ReputationDSL/issues/5#issuecomment-799029630 for ideas but there are a few implementation options to consider.

At a low level there are two user stories to fulfill here-

- [ ] As an integrator of the DSL, I want to be able to define a new reputation datatype and its structure *in my own third-party code*.
- [ ] As an integrator of the DSL, I want the interpreter to throw an error if the wrong datatype is used as an input to a reputation calculation

**Comment by pospi** [comment]
An example of a "new reputation datatype" could be something like "likes".

**Comment by mhuesch** [comment]
this is subsumed by "coherent typechecking of user-defined datatypes", which is captured elsewhere, and seems redundant with #9.
