### ISSUE TITLE
Proof execution of custom type compatibility / incompatibility

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_lang#9]
- [ ] Two different custom datatypes should be declared (eg. "likes" and "upvotes")
- [ ] A calcuation expecting "likes" should error when provided "upvotes"
- [ ] An error should be thrown if "likes" and "upvotes" data is computed against each other

**Comment by pospi** [comment]
Follows on from #7

**Comment by mhuesch** [comment]
this is subsumed by "coherent typechecking of user-defined datatypes", which is captured elsewhere.
